/**
 * Parse DTS Cloud API documentation (JSDoc HTML) into a structured in-memory index,
 * and extract example snippets from api_examples.js.
 *
 * Docs are fetched on-demand from the DTS Cloud server at runtime (see src/index.js);
 * there is no local file parsing.
 */

function normalizeName(name) {
    return name.charAt(0).toLowerCase() + name.slice(1);
}

// (Removed legacy local-Markdown parsers: parseSignature/parseDescription/parseExample/
//  getParamSection/parseTopLevelParams/parseNestedProperties/parseMethodDoc/parseClassDoc/
//  buildDocIndex — unused at runtime. Docs now come from DTS Cloud HTML via parseDocHtml.)

// ── Helpers ───────────────────────────────────────────────────

function formatMethodHelp(doc) {
    const lines = [];
    lines.push(`## ${doc.signature}`);
    lines.push('');
    if (doc.description) lines.push(doc.description);
    lines.push('');
    lines.push('### Parameters');
    for (const p of doc.params) {
        const req = p.required ? '[REQUIRED]' : '[optional]';
        lines.push(`- **${p.name}** (${p.type}) ${req}: ${p.description}`);
        if (p.properties && p.properties.length > 0) {
            lines.push('  Object properties:');
            for (const prop of p.properties) {
                const preq = prop.required ? 'required' : 'optional';
                const def = prop.default ? ` (default: ${prop.default})` : '';
                lines.push(`  - \`${prop.name}\` (${prop.type}) [${preq}]${def}: ${prop.description}`);
            }
        }
    }
    if (doc.example) {
        lines.push('');
        lines.push('### Example');
        lines.push('```javascript');
        lines.push(doc.example);
        lines.push('```');
    }
    // Add RGBA color note if any parameter has Color type
    const hasColorParam = doc.params.some(p =>
        p.type && p.type.toLowerCase().includes('color') ||
        (p.properties || []).some(pp => pp.type && pp.type.toLowerCase().includes('color'))
    );
    if (hasColorParam) {
        lines.push('');
        lines.push('> **Color format**: Use RGBA array `[R, G, B, A]` where each channel is 0~1 (RGB value divided by 255).');
        lines.push('> Example: red=`[1, 0, 0, 1]`, blue=`[0, 0, 1, 1]`, green=`[0, 1, 0, 1]`.');
        lines.push('> Do NOT use string names like `"Color.Red"` — the API cannot resolve them.');
    }
    return lines.join('\n');
}

/**
 * Parse a DTS Cloud API class doc HTML page into the structured docIndex format.
 *
 * The HTML is generated by JSDoc (sunlight-style) and has this structure:
 *
 *   <dt>
 *     <h4 class="name" id="add">
 *       <span class="type-signature"></span>add<span class="signature">(data, fn)</span>
 *     </h4>
 *   </dt>
 *   <dd>
 *     <div class="description"><p>添加一个或多个无人机对象</p></div>
 *     <h5>Parameters:</h5>
 *     <table class="params table table-striped">
 *       <tr><th>Name</th><th>Type</th><th class="last">Description</th></tr>
 *       <tr>
 *         <td class="name"><code>data</code></td>
 *         <td class="type"><span class="param-type">object</span></td>
 *         <td class="description last"><p>desc</p><ul><li><strong>id</strong> (string) desc</li></ul></td>
 *       </tr>
 *     </table>
 *     <h5>Example</h5>
 *     <pre class="sunlight-highlight-javascript">code</pre>
 *   </dd>
 */
function parseDocHtml(html, className) {
    const ns = normalizeName(className);
    const index = {};
    index[ns] = {};

    // --- Helper: decode HTML entities to plain text ---
    function plainText(raw) {
        return raw
            .replace(/<br\s*\/?>/gi, '\n')
            .replace(/<[^>]+>/g, '')
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&nbsp;/g, ' ')
            .replace(/&quot;/g, '"')
            .replace(/&#x27;/g, "'")
            .replace(/&#39;/g, "'")
            .replace(/\s+/g, ' ')
            .trim();
    }

    // Split into method blocks by JSDoc <dt><h4 class="name" id="XXX">
    const methodBlocks = html.split(/<dt>[\s\S]*?<h4\s+class="name"\s+id="([^"]+)"/gi);

    for (let i = 1; i < methodBlocks.length; i += 2) {
        const methodName = methodBlocks[i].trim();
        const block = methodBlocks[i + 1] || '';

        if (!methodName) continue;

        // Skip constructor (has same name as class)
        if (methodName === className) continue;
        const ddMatch = block.match(/<dd>([\s\S]*?)<\/dd>/i);
        if (!ddMatch) continue;

        const ddContent = ddMatch[1];
        if (!ddContent.trim()) continue;

        const doc = { className, methodName };

        // ── Signature: from <span class="signature">(PARAMS)</span> ──
        // The block starts after <h4 class="name" id="XXX"> so the span is right there
        const sigSpan = block.match(/<span\s+class="signature"[^>]*>\(([^)]*)\)<\/span>/i);
        if (sigSpan) {
            doc.rawParams = sigSpan[1];
            doc.signature = `${className}.${methodName}(${doc.rawParams})`;
        } else {
            doc.signature = `${className}.${methodName}(...)`;
        }

        // ── Description: <div class="description"><p>TEXT</p></div> ──
        const descMatch = ddContent.match(/<div\s+class="description"[^>]*>\s*<p>([\s\S]*?)<\/p>\s*<\/div>/i);
        if (descMatch) {
            doc.description = plainText(descMatch[1]);
        }

        // ── Parameters table ──
        // Find the <table class="params ..."> within the dd
        const tableMatch = ddContent.match(/<table\s+class="params[^"]*"[^>]*>([\s\S]*?)<\/table>/i);
        if (tableMatch) {
            doc.params = parseJsdocParams(tableMatch[1]);
        } else {
            doc.params = [];
        }

        // ── Example code ──
        // JSDoc style: <pre class="sunlight-highlight-javascript">CODE</pre>
        const preMatch = ddContent.match(/<pre[^>]*class="[^"]*sunlight-highlight[^"]*"[^>]*>([\s\S]*?)<\/pre>/i);
        if (preMatch) {
            doc.example = preMatch[1]
                .replace(/&lt;/g, '<')
                .replace(/&gt;/g, '>')
                .replace(/&amp;/g, '&')
                .replace(/&nbsp;/g, ' ')
                .replace(/&quot;/g, '"')
                .replace(/&#x27;/g, "'")
                .replace(/&#39;/g, "'")
                .replace(/\r\n/g, '\n')
                .trim();
        }

        index[ns][methodName] = doc;
    }

    return index;
}

/**
 * Parse a JSDoc-style parameter table into the structured params array.
 * Table rows look like:
 *   <tr>
 *     <td class="name"><code>paramName</code></td>
 *     <td class="type"><span class="param-type">type</span></td>
 *     <td class="description last"><p>desc</p><ul><li><strong>prop</strong> (type) desc</li></ul></td>
 *   </tr>
 */
function parseJsdocParams(tableHtml) {
    const params = [];

    // Extract row blocks: <tr> ... </tr>
    const rowRe = /<tr[^>]*>([\s\S]*?)<\/tr>/gi;
    let rowMatch;
    while ((rowMatch = rowRe.exec(tableHtml)) !== null) {
        const row = rowMatch[1];
        if (!row.trim()) continue;

        // Extract td cells
        const cells = [];
        const cellRe = /<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi;
        let cellMatch;
        while ((cellMatch = cellRe.exec(row)) !== null) {
            cells.push(cellMatch[1].trim());
        }

        if (cells.length < 3) continue;

        // Extract plain text from each cell
        const nameHtml = cells[0];
        const typeHtml = cells[1];
        const descHtml = cells.slice(2).join(' ');

        // Name: <code>name</code>
        const nameMatch = nameHtml.match(/<code[^>]*>([\s\S]*?)<\/code>/i);
        const paramName = nameMatch ? nameMatch[1].trim() : nameHtml.replace(/<[^>]+>/g, '').trim();
        if (!paramName || paramName === 'Name' || paramName === '---') continue;

        // Type: <span class="param-type">type</span>
        const types = [];
        const typeRe = /<span\s+class="param-type"[^>]*>([\s\S]*?)<\/span>/gi;
        let tm;
        while ((tm = typeRe.exec(typeHtml)) !== null) {
            types.push(tm[1].trim());
        }
        const paramType = types.length > 0 ? types.join(' | ') : typeHtml.replace(/<[^>]+>/g, '').trim();

        // Description: strip HTML tags for top-level text, then find nested properties
        const descText = descHtml
            .replace(/<\/?p[^>]*>/gi, ' ')
            .replace(/<\/?ul[^>]*>/gi, ' ')
            .replace(/<\/?li[^>]*>/gi, '\n')
            .replace(/<[^>]+>/g, '')
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&nbsp;/g, ' ')
            .replace(/\s+/g, ' ')
            .trim();

        // Detect optional
        const isFn = paramName === 'fn';
        const isOptional = descText.includes('[可选]') || descText.startsWith('可选') || isFn;

        // Parse nested properties from <li> items in description
        let properties = undefined;
        const liMatch = descHtml.match(/<li>([\s\S]*?)<\/li>/gi);
        if (liMatch && liMatch.length > 0) {
            const propTexts = liMatch.map(li => {
                return li.replace(/<\/?li[^>]*>/gi, '')
                    .replace(/<[^>]+>/g, '')
                    .replace(/&amp;/g, '&')
                    .replace(/&nbsp;/g, ' ')
                    .trim();
            }).filter(t => t.length > 0);

            if (propTexts.length > 0) {
                const parsedProps = parseNestedInlineProps(propTexts.join('\n'));
                if (parsedProps.length > 0) {
                    properties = parsedProps;
                }
            }
        }

        params.push({
            name: paramName,
            type: paramType,
            required: !isOptional,
            description: descText,
            properties: properties,
        });
    }

    return params;
}

/**
 * Parse inline nested property definitions from a raw description string.
 *
 * In DTS API docs, almost all nested properties are optional with defaults.
 * Only id/coordinate/coordinates are genuinely required.
 */
function parseNestedInlineProps(rawDesc) {
    const props = [];
    const lines = rawDesc
        .replace(/<br\s*\/?>/gi, '\n')
        .replace(/<\/?[^>]+>/g, '')
        .split(/\n+/);

    for (let line of lines) {
        line = line.trim();
        if (!line) continue;

        const m = line.match(/^(\w[\w.]*)\s*\(([^)]+)\)\s*([\s\S]*)$/);
        if (!m) continue;

        const name = m[1].trim();
        const type = m[2].trim();
        const raw = m[3].replace(/\s+/g, ' ').trim();

        if (name.length > 60) continue;

        // Only id, coordinate, coordinates are truly required at nested level
        const isTrulyRequired = name === 'id' || name === 'coordinate' || name === 'coordinates';

        let defaultValue = null;
        const defMatch = raw.match(/默认值[:：]\s*(.+?)(?:[，,](?:\s*(?:注意|取值|示例|单位|如果|可|支持|设置|默认|用|不|取值范围|仅|包含|如何|具体|参考|详情|索引|分别|即))|\n|$)/);
        if (defMatch) {
            defaultValue = defMatch[1].trim();
        } else {
            const simpleDef = raw.match(/默认值[:：]\s*(.+?)(?:[，。]|\s*$)/);
            if (simpleDef) defaultValue = simpleDef[1].trim();
        }

        const cleanDesc = raw
            .replace(/，默认值[:：].*$/, '')
            .replace(/默认值[:：].*$/, '')
            .replace(/[，,]$/, '')
            .trim();

        props.push({
            name,
            type,
            required: isTrulyRequired,
            description: cleanDesc || name,
            default: defaultValue,
        });
    }

    return props;
}

/**
 * DTS API 所有接口类索引表。
 * 类名（首字母大写）→ 类用途/描述。
 * 用于 dts_doc 未指定类时列出所有可用类。
 * @constant {Array<{name:string, desc:string}>}
 */
const DTS_CLASSES = [
    { name: 'Antenna', desc: '天线' },
    { name: 'BaseObject', desc: '基础对象' },
    { name: 'BattlefieldSimulation', desc: '战场仿真' },
    { name: 'Beam', desc: '光束' },
    { name: 'BoxTrigger', desc: '盒子触发器' },
    { name: 'Camera', desc: '相机' },
    { name: 'CameraTour', desc: '相机巡游' },
    { name: 'CameraTourData', desc: '相机巡游数据' },
    { name: 'CameraTourKeyFrame', desc: '相机巡游关键帧' },
    { name: 'Cesium3DTileset', desc: 'Cesium 3D 瓦片集' },
    { name: 'Coord', desc: '坐标' },
    { name: 'CustomMesh', desc: '自定义网格' },
    { name: 'CustomObject', desc: '自定义对象（通过API添加的模型）' },
    { name: 'CustomTag', desc: '自定义标签' },
    { name: 'DaHuaVideoFusion', desc: '大华视频融合' },
    { name: 'Decal', desc: '贴花' },
    { name: 'DigitalTwinAPI', desc: '数字孪生 API（全局控制）' },
    { name: 'DigitalTwinPlayer', desc: '数字孪生播放器' },
    { name: 'Drone', desc: '无人机' },
    { name: 'DynamicWater', desc: '动态水面' },
    { name: 'EditHelper', desc: '编辑助手' },
    { name: 'ExcavationAnalysis', desc: '超欠挖分析' },
    { name: 'FdExternal', desc: '外部接口' },
    { name: 'FiniteElement', desc: '有限元' },
    { name: 'FiniteElement2', desc: '有限元 2' },
    { name: 'FloodFill', desc: '洪水填充' },
    { name: 'Fluid', desc: '流体' },
    { name: 'GaussianSplatting', desc: '高斯泼溅' },
    { name: 'GeoJSONLayer', desc: 'GeoJSON 图层' },
    { name: 'GlobeTerrain', desc: 'Globe 地形' },
    { name: 'HeatMap', desc: '热力图' },
    { name: 'HeatMap3D', desc: '3D 热力图' },
    { name: 'HighlightArea', desc: '高亮区域' },
    { name: 'HydroDynamic1D', desc: '水动力 1D' },
    { name: 'HydroDynamic2D', desc: '水动力 2D' },
    { name: 'HydrodynamicModel', desc: '水动力模型' },
    { name: 'HydrodynamicModel2', desc: '水动力模型 2' },
    { name: 'ImageryLayer', desc: '影像图层' },
    { name: 'ImageryLayer2', desc: '影像图层 2' },
    { name: 'InfoTree', desc: '信息树（查询图层信息）' },
    { name: 'Light', desc: '灯光' },
    { name: 'Marker', desc: '标记（标注点）' },
    { name: 'Marker3D', desc: '3D 标记' },
    { name: 'MarkerLayer', desc: '标记图层' },
    { name: 'Misc', desc: '杂项' },
    { name: 'OceanHeatMap', desc: '海洋热力图' },
    { name: 'ODLine', desc: 'OD 线' },
    { name: 'Panorama', desc: '全景图' },
    { name: 'Plot', desc: '绘图' },
    { name: 'Polygon', desc: '多边形' },
    { name: 'Polygon3D', desc: '3D 多边形' },
    { name: 'Polyline', desc: '折线' },
    { name: 'QueryOption', desc: '查询选项' },
    { name: 'RadiationPoint', desc: '辐射点' },
    { name: 'River', desc: '河流' },
    { name: 'Satellite', desc: '卫星' },
    { name: 'Settings', desc: '设置' },
    { name: 'SettingsPanel', desc: '设置面板' },
    { name: 'ShapeFileLayer', desc: 'Shapefile 图层' },
    { name: 'SignalWave', desc: '信号波' },
    { name: 'SmoothedParticleHydrodynamics', desc: '光滑粒子流体动力学' },
    { name: 'SplineMesh', desc: '样条网格' },
    { name: 'Tag', desc: '标签' },
    { name: 'TileLayer', desc: '瓦片图层（场景中的基础图层）' },
    { name: 'Tools', desc: '工具' },
    { name: 'TopologyLine', desc: '拓扑线' },
    { name: 'TrafficSimulation', desc: '交通仿真' },
    { name: 'Train', desc: '火车' },
    { name: 'VectorField', desc: '向量场' },
    { name: 'Vehicle', desc: '车辆' },
    { name: 'Vehicle2', desc: '车辆 2' },
    { name: 'VideoProjection', desc: '视频投影' },
    { name: 'WaterFlowField', desc: '水流场' },
    { name: 'WaterMesh', desc: '水网格' },
    { name: 'Weather', desc: '天气' },
];

/**
 * 返回格式化的 DTS 类列表文本。
 */
function formatClassList() {
    const lines = ['# DTS API 类索引', ''];
    for (const cls of DTS_CLASSES) {
        lines.push(`- **${cls.name}**: ${cls.desc}`);
    }
    lines.push('');
    lines.push('---');
    lines.push('**使用提示**:');
    lines.push('- 场景中的基础图层都是 `tileLayer`，通过 `TileLayer` 接口类控制');
    lines.push('- 通过 `customObject.add()` 添加的自定义模型是 `CustomObject`，用 `CustomObject` 接口类控制');
    lines.push('- 二者在场景中看起来都是模型/图层，但 API 完全不互通，必须用对应的接口类操作');
    lines.push('- 查询图层信息用 `InfoTree`（infoTree.get）');
    lines.push('- 查询某个类的详细信息: `dts_doc({ class: "类名" })`');
    lines.push('- 位置定位常用: `focus`（自动定位）、`flyAround`（环绕）、`Camera.set`（直接设camera坐标）');
    lines.push('- **颜色格式**: DTS 颜色使用 RGBA 数组 `[R, G, B, A]`，每个通道为 0~1 浮点数（即原始 RGB 值除以 255）。例如红色=`[1,0,0,1]`，蓝色=`[0,0,1,1]`，白色=`[1,1,1,1]`。不要使用 `Color.Red` 这种字符串常量，API 无法解析');
    return lines.join('\n');
}

/**
 * 从 api_examples.js 源码中提取指定类+方法的示例函数体。
 *
 * 函数命名约定：test_{ClassName}_{methodName}()
 * 例如：test_Train_add()、test_Marker_focus()
 * 支持 function 和 async function 两种声明。
 *
 * @param {string} source - api_examples.js 的完整源码
 * @param {string} className - 类名，首字母大写，如 "Train"
 * @param {string} methodName - 方法名，如 "add"
 * @returns {string|null} 提取到的函数源码（含函数声明），或 null
 */
function extractApiExample(source, className, methodName) {
    // 生成函数名：test_{classNameLower}_{methodName}
    const funcName = `test_${className.charAt(0).toLowerCase() + className.slice(1)}_${methodName}`;

    // 匹配 function xxx() 或 async function xxx()
    // 注意：函数名可能出现在注释或字符串中，所以先找行首的 function
    const funcRe = new RegExp(
        `(?:^|\\n)\\s*(?:async\\s+)?function\\s+${funcName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\([^)]*\\)\\s*\\{`,
        'm'
    );
    const match = funcRe.exec(source);
    if (!match) return null;

    const funcStart = match.index;
    // 函数体从第一个 { 开始
    const bodyStart = source.indexOf('{', match.index) + 1;
    if (bodyStart === 0) return null;

    // 括号计数法提取完整函数体
    let depth = 1;
    let pos = bodyStart;
    while (depth > 0 && pos < source.length) {
        const ch = source[pos];
        if (ch === '{') depth++;
        else if (ch === '}') depth--;
        pos++;
    }

    return source.slice(funcStart, pos);
}

module.exports = { formatMethodHelp, normalizeName, parseDocHtml, parseJsdocParams, parseNestedInlineProps, DTS_CLASSES, formatClassList, extractApiExample };
